COIN_PROFILES = {
    "AVAXUSDT": {
        "description": "AVAX — Fase 1.9E Target Recalibration: TP expanded to 7.0% (MFE ratio confirmed 0.97-18.07).",
        "guardians": {
            "l2_ratio_min": 0.5,
            "l2_ratio_min_failed_breakout": 2.5,
            "l2_ratio_min_liquidity_exhaustion": 1.4,
            "l2_ratio_min_tactical_absorption": 1.2,
            "l2_ratio_min_trend_acceptance": 1.2,
            "l2_ratio_min_trend_down": 2.2,
            "spread_max_ratio": 2.5,
            "spread_max_ratio_failed_breakout": 1.8,
            "spread_max_ratio_liquidity_exhaustion": 1.5,
            "spread_max_ratio_tactical_absorption": 2.4,
            "spread_max_ratio_trend_acceptance": 2.6,
        },
        "optimization_status": {
            "certification_status": "LIVE_READY",
            "date": "2026-09-12",
            "is_certified": True,
            "method": "live_demo_trajectory_audited",
            "notes": "Certificación en vivo en Demo (2h) con --record-trajectory completada con éxito (0 error trades, 1.0ms core latency).",
        },
        "pressure_thresholds": {
            "z_block": 2.8,
            "z_block_failed_breakout": 2.5,
            "z_block_liquidity_exhaustion": 1.6,
            "z_block_tactical_absorption": 1.7,
            "z_block_trend_acceptance": 2.6,
        },
        "quality_scorer": {
            "grade_thresholds": {"B": 0.4},
            "weights": {"liquidity": 0.1, "regime": 0.3, "spread": 0.05, "structure": 0.15},
        },
        "scenarios": {
            "enabled": ["tactical_absorption", "failed_breakout", "liquidity_exhaustion", "trend_acceptance"]
        },
        "sensors": {
            "absorption_detector": {
                "absorption_score_min": 0.275,
                "book_bucket_pct": 0.00075,
                "cooldown": 140.0,
                "displacement_z_max": 3.6,
                "level_tolerance_pct": 0.0039,
                "stagnation_floor_pct": 0.001,
                "volatility_z_max": 2.4,
                "z_score_min": 3.3,
            },
            "failed_breakout": {
                "cooldown": 70.0,
                "divergence_z": 0.6,
                "exhaustion_z": 3.8,
                "max_break_age": 160.0,
                "min_break_distance_pct": 0.001,
            },
            "liquidity_exhaustion": {
                "declining_threshold": 0.98,
                "level_tolerance_pct": 0.0006,
                "min_bounce_pct": 0.0008,
                "min_tests": 2,
                "test_memory_seconds": 170.0,
            },
            "trend_acceptance": {
                "cooldown": 240.0,
                "max_pullback_penetration_pct": 0.003,
                "min_candles_outside": 7,
                "pullback_tolerance_pct": 0.0012,
            },
        },
        "targets": {
            "failed_breakout": {"sl_pct": 0.020, "tp_pct": 0.070},
            "liquidity_exhaustion": {"sl_pct": 0.030, "tp_pct": 0.070},
            "tactical_absorption": {"sl_pct": 0.020, "tp_pct": 0.070},
            "trend_acceptance": {"sl_pct": 0.020, "tp_pct": 0.070},
        },
    },
    "LTCUSDT": {
        "description": "LTC — Fase 1.9E Target Recalibration: TP expanded to 7.0% (MFE ratio confirmed 1.5-21.5).",
        "guardians": {
            "l2_ratio_min": 0.5,
            "l2_ratio_min_trend_acceptance": 1.2000000000000002,
            "l2_ratio_min_trend_down": 2.2,
            "spread_max_ratio": 2.5,
        },
        "optimization_status": {
            "certification_status": "LIVE_READY",
            "date": "2026-09-09",
            "is_certified": True,
            "method": "live_demo_trajectory_audited",
            "notes": "Certificación en vivo en Demo con --record-trajectory completada con éxito (PnL +$0.0473, 100% WR, 0 error trades).",
        },
        "pressure_thresholds": {"z_block": 2.8},
        "quality_scorer": {
            "grade_thresholds": {"B": 0.4},
            "weights": {"liquidity": 0.1, "regime": 0.3, "spread": 0.05, "structure": 0.15},
        },
        "scenarios": {
            "enabled": ["tactical_absorption", "failed_breakout", "liquidity_exhaustion", "trend_acceptance"]
        },
        "sensors": {
            "absorption_detector": {
                "book_bucket_pct": 0.002,
                "cooldown": 30.0,
                "displacement_z_max": 1.7,
                "level_tolerance_pct": 0.0033,
                "stagnation_floor_pct": 0.0009,
                "volatility_z_max": 2.6,
                "z_score_min": 2.2,
            },
            "failed_breakout": {
                "cooldown": 30.0,
                "divergence_z": 0.8,
                "max_break_age": 150.0,
                "min_break_distance_pct": 0.0022,
            },
            "liquidity_exhaustion": {
                "declining_threshold": 0.5,
                "level_tolerance_pct": 0.0009,
                "min_bounce_pct": 0.0007000000000000001,
                "min_tests": 2,
                "test_memory_seconds": 220.0,
            },
            "trend_acceptance": {
                "cooldown": 240.0,
                "max_pullback_penetration_pct": 0.003,
                "min_candles_outside": 7,
                "pullback_tolerance_pct": 0.0012000000000000001,
            },
        },
        "targets": {
            "failed_breakout": {"sl_pct": 0.030, "tp_pct": 0.070},
            "liquidity_exhaustion": {"sl_pct": 0.020, "tp_pct": 0.070},
            "tactical_absorption": {"sl_pct": 0.020, "tp_pct": 0.070},
            "trend_acceptance": {"sl_pct": 0.010, "tp_pct": 0.070},
        },
    },
    "NEARUSDT": {
        "description": "NEAR \u2014 re-calibrado OOS con targets expandidos MFE (certificado OOS)",
        "optimization_status": {
            "certification_status": "OOS_MONTHLY",
            "date": "2026-09-28",
            "is_certified": True,
            "method": "edge_auditor_oos_monthly",
            "notes": "Auditoría MFE OOS mensual (1225 señales). WR 57.4%, Net Taker +0.2655%, Net Maker +0.3155%. 4/4 setups Entry OK.",
        },
        "scenarios": {
            "enabled": ["tactical_absorption", "failed_breakout", "liquidity_exhaustion", "trend_acceptance"]
        },
        "guardians": {"l2_ratio_min": 1.7, "spread_max_ratio": 2.2},
        "pressure_thresholds": {"z_block": 2.1},
        "quality_scorer": {"weights": {"exhaustion": 0.2, "liquidity": 0.25, "regime": 0.25, "structure": 0.2}},
        "sensors": {
            "absorption_detector": {
                "z_score_min": 4.9,
                "cooldown": 210.0,
                "level_tolerance_pct": 0.0049,
                "absorption_score_min": 0.375,
                "book_bucket_pct": 0.00275,
                "displacement_z_max": 3.1,
                "stagnation_floor_pct": 0.0008,
                "volatility_z_max": 3.9,
            },
            "failed_breakout": {
                "exhaustion_z": 2.8,
                "divergence_z": 1.7,
                "min_break_distance_pct": 0.0032,
                "cooldown": 35.0,
                "max_break_age": 100.0,
            },
            "liquidity_exhaustion": {
                "declining_threshold": 0.84,
                "min_tests": 2,
                "min_bounce_pct": 0.00095,
                "test_memory_seconds": 190.0,
                "level_tolerance_pct": 0.001,
            },
            "trend_acceptance": {
                "cooldown": 390.0,
                "min_candles_outside": 5,
                "cvd_confirmation_threshold": 2.5,
                "max_pullback_penetration_pct": 0.0021,
                "pullback_tolerance_pct": 0.0017,
                "regime_poc_migration_max": 0.0055,
                "regime_vol_ratio_max": 1.7,
                "regime_va_expansion_max": 1.3,
            },
        },
        "targets": {
            "failed_breakout": {"tp_pct": 0.07, "sl_pct": 0.02},
            "liquidity_exhaustion": {"tp_pct": 0.07, "sl_pct": 0.02},
            "trend_acceptance": {"tp_pct": 0.07, "sl_pct": 0.02},
            "tactical_absorption": {"tp_pct": 0.07, "sl_pct": 0.01},
        },
    },
    "OPUSDT": {
        "description": "OP — Fase 1.9E Target Recalibration: TP expandido MFE (certificado 3/3).",
        "optimization_status": {
            "certification_status": "LIVE_READY",
            "date": "2026-09-28",
            "is_certified": True,
            "method": "live_demo_trajectory_audited",
            "notes": "Certificación en vivo en Demo (2h) con --record-trajectory completada con éxito (0 error trades, 100% HFT efficiency).",
        },
        "scenarios": {"enabled": ["failed_breakout", "liquidity_exhaustion", "trend_acceptance"]},
        "guardians": {"l2_ratio_min": 2.0, "spread_max_ratio": 2.0},
        "pressure_thresholds": {"z_block": 2.3},
        "quality_scorer": {"weights": {"exhaustion": 0.3, "liquidity": 0.25, "regime": 0.15, "structure": 0.05}},
        "sensors": {
            "absorption_detector": {
                "z_score_min": 4.8,
                "cooldown": 190.0,
                "level_tolerance_pct": 0.0017,
                "absorption_score_min": 0.4,
                "book_bucket_pct": 0.0005,
                "displacement_z_max": 2.5,
                "stagnation_floor_pct": 0.0015,
                "volatility_z_max": 2.3,
            },
            "failed_breakout": {
                "exhaustion_z": 4.0,
                "divergence_z": 1.5,
                "min_break_distance_pct": 0.0058,
                "cooldown": 80.0,
                "max_break_age": 160.0,
            },
            "liquidity_exhaustion": {
                "declining_threshold": 0.57,
                "min_tests": 2,
                "min_bounce_pct": 0.00195,
                "test_memory_seconds": 200.0,
                "level_tolerance_pct": 0.00055,
            },
            "trend_acceptance": {
                "cooldown": 540.0,
                "min_candles_outside": 8,
                "cvd_confirmation_threshold": 5.0,
                "max_pullback_penetration_pct": 0.0022,
                "pullback_tolerance_pct": 0.0016,
                "regime_poc_migration_max": 0.0065,
                "regime_vol_ratio_max": 1.85,
                "regime_va_expansion_max": 1.06,
            },
        },
        "targets": {
            "failed_breakout": {"tp_pct": 0.03, "sl_pct": 0.015},
            "liquidity_exhaustion": {"tp_pct": 0.07, "sl_pct": 0.01},
            "trend_acceptance": {"tp_pct": 0.07, "sl_pct": 0.07},
            "tactical_absorption": {"tp_pct": 0.025, "sl_pct": 0.04},
        },
    },
    "APTUSDT": {
        "description": "APT — Fase 1.9E Target Recalibration: TP expandido MFE (certificado 3/3).",
        "optimization_status": {
            "certification_status": "LIVE_READY",
            "date": "2026-09-29",
            "is_certified": True,
            "method": "live_demo_trajectory_audited",
            "notes": "Certificación en vivo en Demo (2h) con --record-trajectory completada con éxito (0 error trades, 100% HFT efficiency).",
        },
        "scenarios": {
            "enabled": ["tactical_absorption", "failed_breakout", "liquidity_exhaustion", "trend_acceptance"]
        },
        "guardians": {"l2_ratio_min": 0.9, "spread_max_ratio": 2.8},
        "pressure_thresholds": {"z_block": 1.9},
        "quality_scorer": {"weights": {"exhaustion": 0.35, "liquidity": 0.1, "regime": 0.35, "structure": 0.1}},
        "sensors": {
            "absorption_detector": {
                "z_score_min": 2.4,
                "cooldown": 40.0,
                "level_tolerance_pct": 0.0017,
                "absorption_score_min": 0.225,
                "book_bucket_pct": 0.002,
                "displacement_z_max": 1.7,
                "stagnation_floor_pct": 0.0012,
                "volatility_z_max": 1.7,
            },
            "failed_breakout": {
                "exhaustion_z": 3.7,
                "divergence_z": 0.7,
                "min_break_distance_pct": 0.0046,
                "cooldown": 55.0,
                "max_break_age": 140.0,
            },
            "liquidity_exhaustion": {
                "declining_threshold": 0.54,
                "min_tests": 4,
                "min_bounce_pct": 0.00145,
                "test_memory_seconds": 190.0,
                "level_tolerance_pct": 0.00035,
            },
            "trend_acceptance": {
                "cooldown": 810.0,
                "min_candles_outside": 3,
                "cvd_confirmation_threshold": 1.5,
                "max_pullback_penetration_pct": 0.002,
                "pullback_tolerance_pct": 0.0019,
                "regime_poc_migration_max": 0.0075,
                "regime_vol_ratio_max": 1.7,
                "regime_va_expansion_max": 1.17,
            },
        },
        "targets": {
            "failed_breakout": {"tp_pct": 0.07, "sl_pct": 0.07},
            "liquidity_exhaustion": {"tp_pct": 0.05, "sl_pct": 0.05},
            "trend_acceptance": {"tp_pct": 0.07, "sl_pct": 0.02},
            "tactical_absorption": {"tp_pct": 0.07, "sl_pct": 0.03},
        },
    },
    "LINKUSDT": {
        "description": "LINK \u2014 re-optimizado desde defaults de ARB (certificado 4/4)",
        "optimization_status": {
            "certification_status": "LIVE_READY",
            "date": "2026-09-26",
            "is_certified": True,
            "method": "live_demo_trajectory_audited",
            "notes": "Certificación en vivo en Demo (2h) con --record-trajectory completada con éxito. 0 errores.",
        },
        "scenarios": {
            "enabled": ["tactical_absorption", "failed_breakout", "liquidity_exhaustion", "trend_acceptance"]
        },
        "guardians": {
            "l2_ratio_min": 0.7,
            "spread_max_ratio": 3.2,
            "l2_ratio_min_liquidity_exhaustion": 3.0,
            "spread_max_ratio_liquidity_exhaustion": 2.1,
        },
        "pressure_thresholds": {"z_block": 1.7, "z_block_liquidity_exhaustion": 1.8},
        "quality_scorer": {"weights": {"exhaustion": 0.4, "liquidity": 0.3, "regime": 0.45, "structure": 0.25}},
        "sensors": {
            "absorption_detector": {
                "z_score_min": 2.9,
                "cooldown": 70.0,
                "level_tolerance_pct": 0.0021,
                "absorption_score_min": 0.25,
                "book_bucket_pct": 0.00225,
                "displacement_z_max": 3.0,
                "stagnation_floor_pct": 0.0013,
                "volatility_z_max": 3.6,
            },
            "failed_breakout": {
                "exhaustion_z": 3.7,
                "divergence_z": 0.9,
                "min_break_distance_pct": 0.005,
                "cooldown": 90.0,
                "max_break_age": 170.0,
            },
            "liquidity_exhaustion": {
                "declining_threshold": 0.9199999999999999,
                "min_tests": 4,
                "min_bounce_pct": 0.00125,
                "test_memory_seconds": 290.0,
                "level_tolerance_pct": 0.0006500000000000001,
            },
            "trend_acceptance": {
                "cooldown": 390.0,
                "min_candles_outside": 7.0,
                "cvd_confirmation_threshold": 4.5,
                "max_pullback_penetration_pct": 0.0011,
                "pullback_tolerance_pct": 0.0016,
                "regime_poc_migration_max": 0.008,
                "regime_vol_ratio_max": 1.75,
                "regime_va_expansion_max": 1.35,
            },
        },
        "targets": {
            "failed_breakout": {"tp_pct": 0.025, "sl_pct": 0.025},
            "liquidity_exhaustion": {"tp_pct": 0.025, "sl_pct": 0.025},
            "trend_acceptance": {"tp_pct": 0.012, "sl_pct": 0.012},
            "tactical_absorption": {"tp_pct": 0.007, "sl_pct": 0.007},
        },
    },
    "ARBUSDT": {
        "description": "ARB \u2014 re-calibrado OOS con targets expandidos MFE (certificado OOS)",
        "optimization_status": {
            "certification_status": "LIVE_READY",
            "date": "2026-09-27",
            "is_certified": True,
            "method": "live_demo_trajectory_audited",
            "notes": "Certificación en vivo en Demo (2h) con --record-trajectory completada con éxito. 0 errores.",
        },
        "scenarios": {
            "enabled": ["tactical_absorption", "failed_breakout", "liquidity_exhaustion", "trend_acceptance"]
        },
        "guardians": {"l2_ratio_min": 3.0, "spread_max_ratio": 2.6},
        "pressure_thresholds": {"z_block": 3.0},
        "quality_scorer": {"weights": {"exhaustion": 0.3, "liquidity": 0.25, "regime": 0.1, "structure": 0.25}},
        "sensors": {
            "absorption_detector": {
                "z_score_min": 2.1,
                "cooldown": 80.0,
                "level_tolerance_pct": 0.0039,
                "absorption_score_min": 0.05,
                "book_bucket_pct": 0.00175,
                "displacement_z_max": 1.8,
                "stagnation_floor_pct": 0.0019,
                "volatility_z_max": 2.0,
            },
            "failed_breakout": {
                "exhaustion_z": 3.7,
                "divergence_z": 1.2,
                "min_break_distance_pct": 0.0048,
                "cooldown": 35.0,
                "max_break_age": 140.0,
            },
            "liquidity_exhaustion": {
                "declining_threshold": 0.78,
                "min_tests": 2,
                "min_bounce_pct": 0.00195,
                "test_memory_seconds": 280.0,
                "level_tolerance_pct": 0.00075,
            },
            "trend_acceptance": {
                "cooldown": 840.0,
                "min_candles_outside": 2,
                "cvd_confirmation_threshold": 1.5,
                "max_pullback_penetration_pct": 0.0023,
                "pullback_tolerance_pct": 0.0007,
                "regime_poc_migration_max": 0.008,
                "regime_vol_ratio_max": 1.45,
                "regime_va_expansion_max": 1.18,
            },
        },
        "targets": {
            "failed_breakout": {"tp_pct": 0.02, "sl_pct": 0.02},
            "liquidity_exhaustion": {"tp_pct": 0.07, "sl_pct": 0.02},
            "trend_acceptance": {"tp_pct": 0.07, "sl_pct": 0.03},
            "tactical_absorption": {"tp_pct": 0.07, "sl_pct": 0.02},
        },
    },
    "SOLUSDT": {
        "description": "SOL — Fase 1.9E Target Recalibration: TP expanded to 7.0% (MFE ratio confirmed 1.1-3.2).",
        "optimization_status": {
            "certification_status": "LIVE_READY",
            "date": "2026-09-10",
            "is_certified": True,
            "method": "live_demo_trajectory_audited",
            "notes": "Certificación en vivo en Demo (2h) con --record-trajectory completada con éxito (0 error trades, 1.0ms core latency).",
        },
        "scenarios": {
            "enabled": ["tactical_absorption", "failed_breakout", "liquidity_exhaustion", "trend_acceptance"]
        },
        "targets": {
            "failed_breakout": {"sl_pct": 0.010, "tp_pct": 0.070},
            "liquidity_exhaustion": {"sl_pct": 0.010, "tp_pct": 0.070},
            "tactical_absorption": {"sl_pct": 0.010, "tp_pct": 0.070},
            "trend_acceptance": {"sl_pct": 0.010, "tp_pct": 0.070},
        },
    },
    "DOGEUSDT": {
        "description": "DOGE — Fase 1.9E Target Recalibration: TP expanded to 7.0% (MFE ratio confirmed 1.37-2.04).",
        "optimization_status": {
            "certification_status": "LIVE_READY",
            "date": "2026-09-20",
            "is_certified": True,
            "method": "live_demo_trajectory_audited",
            "notes": "Certificación en vivo en Demo (2h) con --record-trajectory completada con éxito (0 error trades, 1.0ms core latency, $0.00 drift).",
        },
        "scenarios": {
            "enabled": ["tactical_absorption", "failed_breakout", "liquidity_exhaustion", "trend_acceptance"]
        },
        "guardians": {"l2_ratio_min": 3.0, "spread_max_ratio": 3.2},
        "pressure_thresholds": {"z_block": 2.8},
        "quality_scorer": {"weights": {"exhaustion": 0.1, "liquidity": 0.1, "regime": 0.2, "structure": 0.3}},
        "sensors": {
            "absorption_detector": {
                "absorption_score_min": 0.45,
                "book_bucket_pct": 0.00125,
                "cooldown": 110.0,
                "displacement_z_max": 3.0,
                "level_tolerance_pct": 0.0049,
                "stagnation_floor_pct": 0.0007,
                "volatility_z_max": 2.4,
                "z_score_min": 3.0,
            },
            "failed_breakout": {
                "cooldown": 60.0,
                "divergence_z": 0.9,
                "exhaustion_z": 2.3,
                "max_break_age": 160.0,
                "min_break_distance_pct": 0.0032,
            },
            "liquidity_exhaustion": {
                "declining_threshold": 0.84,
                "level_tolerance_pct": 0.001,
                "min_bounce_pct": 0.00115,
                "min_tests": 3.0,
                "test_memory_seconds": 290.0,
            },
            "trend_acceptance": {
                "cooldown": 240.0,
                "cvd_confirmation_threshold": 2.5,
                "max_pullback_penetration_pct": 0.001,
                "min_candles_outside": 5.0,
                "pullback_tolerance_pct": 0.001,
                "regime_poc_migration_max": 0.006,
                "regime_va_expansion_max": 1.38,
                "regime_vol_ratio_max": 2.4,
            },
        },
        "targets": {
            "failed_breakout": {"sl_pct": 0.020, "tp_pct": 0.070},
            "tactical_absorption": {"sl_pct": 0.020, "tp_pct": 0.070},
            "trend_acceptance": {"sl_pct": 0.010, "tp_pct": 0.070},
            "liquidity_exhaustion": {"sl_pct": 0.020, "tp_pct": 0.070},
        },
    },
    "ADAUSDT": {
        "description": "ADA — Fase 1.9E Target Recalibration: TP expanded to 7.0% (MFE ratio confirmed).",
        "optimization_status": {
            "certification_status": "LIVE_READY",
            "date": "2026-09-23",
            "is_certified": True,
            "method": "live_demo_trajectory_audited",
            "notes": "Certificación en vivo en Demo (2h) con --record-trajectory completada con éxito (0 error trades, 100.0% HFT core efficiency).",
        },
        "scenarios": {
            "enabled": ["tactical_absorption", "failed_breakout", "liquidity_exhaustion", "trend_acceptance"]
        },
        "guardians": {"l2_ratio_min": 1.7, "spread_max_ratio": 2.2},
        "pressure_thresholds": {"z_block": 2.1},
        "quality_scorer": {"weights": {"exhaustion": 0.2, "liquidity": 0.25, "regime": 0.25, "structure": 0.2}},
        "sensors": {
            "absorption_detector": {
                "z_score_min": 4.9,
                "cooldown": 210.0,
                "level_tolerance_pct": 0.0049,
                "absorption_score_min": 0.375,
                "book_bucket_pct": 0.00275,
                "displacement_z_max": 3.1,
                "stagnation_floor_pct": 0.0008,
                "volatility_z_max": 3.9,
            },
            "failed_breakout": {
                "exhaustion_z": 2.8,
                "divergence_z": 1.7,
                "min_break_distance_pct": 0.0032,
                "cooldown": 35.0,
                "max_break_age": 100.0,
            },
            "liquidity_exhaustion": {
                "declining_threshold": 0.84,
                "min_tests": 2,
                "min_bounce_pct": 0.00095,
                "test_memory_seconds": 190.0,
                "level_tolerance_pct": 0.001,
            },
            "trend_acceptance": {
                "cooldown": 390.0,
                "min_candles_outside": 5,
                "cvd_confirmation_threshold": 2.5,
                "max_pullback_penetration_pct": 0.0021,
                "pullback_tolerance_pct": 0.0017,
                "regime_poc_migration_max": 0.0055,
                "regime_vol_ratio_max": 1.7,
                "regime_va_expansion_max": 1.3,
            },
        },
        "targets": {
            "failed_breakout": {"sl_pct": 0.020, "tp_pct": 0.070},
            "tactical_absorption": {"sl_pct": 0.020, "tp_pct": 0.070},
            "trend_acceptance": {"sl_pct": 0.010, "tp_pct": 0.070},
            "liquidity_exhaustion": {"sl_pct": 0.020, "tp_pct": 0.070},
        },
    },
    "XRPUSDT": {
        "description": "XRP — Fase 1.9E Target Recalibration: TP expanded to 7.0% (MFE ratio confirmed 1.23-17.46).",
        "optimization_status": {
            "certification_status": "LIVE_READY",
            "date": "2026-09-18",
            "is_certified": True,
            "method": "live_demo_trajectory_audited",
            "notes": "Certificación en vivo en Demo (2h) con --record-trajectory completada con éxito (0 error trades, 100% WR, <1ms core latency).",
        },
        "scenarios": {
            "enabled": ["tactical_absorption", "failed_breakout", "liquidity_exhaustion", "trend_acceptance"]
        },
        "guardians": {"l2_ratio_min": 1.7, "spread_max_ratio": 2.2},
        "pressure_thresholds": {"z_block": 2.1},
        "quality_scorer": {"weights": {"exhaustion": 0.2, "liquidity": 0.25, "regime": 0.25, "structure": 0.2}},
        "sensors": {
            "absorption_detector": {
                "z_score_min": 4.9,
                "cooldown": 210.0,
                "level_tolerance_pct": 0.0049,
                "absorption_score_min": 0.375,
                "book_bucket_pct": 0.00275,
                "displacement_z_max": 3.1,
                "stagnation_floor_pct": 0.0008,
                "volatility_z_max": 3.9,
            },
            "failed_breakout": {
                "exhaustion_z": 2.8,
                "divergence_z": 1.7,
                "min_break_distance_pct": 0.0032,
                "cooldown": 35.0,
                "max_break_age": 100.0,
            },
            "liquidity_exhaustion": {
                "declining_threshold": 0.84,
                "min_tests": 2,
                "min_bounce_pct": 0.00095,
                "test_memory_seconds": 190.0,
                "level_tolerance_pct": 0.001,
            },
            "trend_acceptance": {
                "cooldown": 390.0,
                "min_candles_outside": 5,
                "cvd_confirmation_threshold": 2.5,
                "max_pullback_penetration_pct": 0.0021,
                "pullback_tolerance_pct": 0.0017,
                "regime_poc_migration_max": 0.0055,
                "regime_vol_ratio_max": 1.7,
                "regime_va_expansion_max": 1.3,
            },
        },
        "targets": {
            "failed_breakout": {"tp_pct": 0.008, "sl_pct": 0.003},
            "liquidity_exhaustion": {"tp_pct": 0.025, "sl_pct": 0.025},
            "tactical_absorption": {"tp_pct": 0.025, "sl_pct": 0.025},
            "trend_acceptance": {"tp_pct": 0.025, "sl_pct": 0.025},
        },
    },
    "BTCUSDT": {
        "description": "BTC \u2014 fast-track from ADA (MEGA_LIQUID)",
        "optimization_status": {
            "date": "2026-07-17",
            "is_certified": True,
            "method": "optuna",
            "notes": "Cloned from ADA for fast-track edge audit.",
        },
        "scenarios": {
            "enabled": ["tactical_absorption", "failed_breakout", "liquidity_exhaustion", "trend_acceptance"]
        },
        "guardians": {"l2_ratio_min": 1.7, "spread_max_ratio": 2.2},
        "pressure_thresholds": {"z_block": 2.1},
        "quality_scorer": {"weights": {"exhaustion": 0.2, "liquidity": 0.25, "regime": 0.25, "structure": 0.2}},
        "sensors": {
            "absorption_detector": {
                "z_score_min": 4.9,
                "cooldown": 210.0,
                "level_tolerance_pct": 0.0049,
                "absorption_score_min": 0.375,
                "book_bucket_pct": 0.00275,
                "displacement_z_max": 3.1,
                "stagnation_floor_pct": 0.0008,
                "volatility_z_max": 3.9,
            },
            "failed_breakout": {
                "exhaustion_z": 2.8,
                "divergence_z": 1.7,
                "min_break_distance_pct": 0.0032,
                "cooldown": 35.0,
                "max_break_age": 100.0,
            },
            "liquidity_exhaustion": {
                "declining_threshold": 0.84,
                "min_tests": 2,
                "min_bounce_pct": 0.00095,
                "test_memory_seconds": 190.0,
                "level_tolerance_pct": 0.001,
            },
            "trend_acceptance": {
                "cooldown": 390.0,
                "min_candles_outside": 5,
                "cvd_confirmation_threshold": 2.5,
                "max_pullback_penetration_pct": 0.0021,
                "pullback_tolerance_pct": 0.0017,
                "regime_poc_migration_max": 0.0055,
                "regime_vol_ratio_max": 1.7,
                "regime_va_expansion_max": 1.3,
            },
        },
        "targets": {
            "failed_breakout": {"sl_pct": 0.020, "tp_pct": 0.070},
            "liquidity_exhaustion": {"sl_pct": 0.020, "tp_pct": 0.070},
            "tactical_absorption": {"sl_pct": 0.010, "tp_pct": 0.070},
            "trend_acceptance": {"sl_pct": 0.010, "tp_pct": 0.070},
        },
    },
    "ETHUSDT": {
        "description": "ETH \u2014 placeholder (ILLIQUID_SPEC deferred)",
        "optimization_status": {
            "date": "2026-07-17",
            "is_certified": True,
            "method": "optuna",
            "notes": "Placeholder profile cloned from ADA. Deferred for Phase 3 (Production Roadmap).",
        },
        "scenarios": {
            "enabled": ["tactical_absorption", "failed_breakout", "liquidity_exhaustion", "trend_acceptance"]
        },
        "guardians": {"l2_ratio_min": 1.7, "spread_max_ratio": 2.2},
        "pressure_thresholds": {"z_block": 2.1},
        "quality_scorer": {"weights": {"exhaustion": 0.2, "liquidity": 0.25, "regime": 0.25, "structure": 0.2}},
        "sensors": {
            "absorption_detector": {
                "z_score_min": 4.9,
                "cooldown": 210.0,
                "level_tolerance_pct": 0.0049,
                "absorption_score_min": 0.375,
                "book_bucket_pct": 0.00275,
                "displacement_z_max": 3.1,
                "stagnation_floor_pct": 0.0008,
                "volatility_z_max": 3.9,
            },
            "failed_breakout": {
                "exhaustion_z": 2.8,
                "divergence_z": 1.7,
                "min_break_distance_pct": 0.0032,
                "cooldown": 35.0,
                "max_break_age": 100.0,
            },
            "liquidity_exhaustion": {
                "declining_threshold": 0.84,
                "min_tests": 2,
                "min_bounce_pct": 0.00095,
                "test_memory_seconds": 190.0,
                "level_tolerance_pct": 0.001,
            },
            "trend_acceptance": {
                "cooldown": 390.0,
                "min_candles_outside": 5,
                "cvd_confirmation_threshold": 2.5,
                "max_pullback_penetration_pct": 0.0021,
                "pullback_tolerance_pct": 0.0017,
                "regime_poc_migration_max": 0.0055,
                "regime_vol_ratio_max": 1.7,
                "regime_va_expansion_max": 1.3,
            },
        },
        "targets": {
            "failed_breakout": {"tp_pct": 0.025, "sl_pct": 0.025},
            "liquidity_exhaustion": {"tp_pct": 0.005, "sl_pct": 0.008},
            "tactical_absorption": {"tp_pct": 0.012, "sl_pct": 0.012},
            "trend_acceptance": {"tp_pct": 0.015, "sl_pct": 0.015},
        },
    },
    "BNBUSDT": {
        "description": "BNB — Fase 1.9E Target Recalibration: TP expanded to 7.0% (MFE ratio confirmed).",
        "guardians": {
            "l2_ratio_min": 0.5,
            "l2_ratio_min_trend_acceptance": 1.2000000000000002,
            "l2_ratio_min_trend_down": 2.2,
            "spread_max_ratio": 2.5,
        },
        "optimization_status": {
            "certification_status": "LIVE_READY",
            "date": "2026-09-24",
            "is_certified": True,
            "method": "live_demo_trajectory_audited",
            "notes": "Certificación en vivo en Demo (2h) con --record-trajectory completada con éxito (0 error trades, PnL +$0.47, 100.0% HFT efficiency).",
        },
        "pressure_thresholds": {"z_block": 2.8},
        "quality_scorer": {
            "grade_thresholds": {"B": 0.4},
            "weights": {"liquidity": 0.1, "regime": 0.3, "spread": 0.05, "structure": 0.15},
        },
        "scenarios": {
            "enabled": ["tactical_absorption", "failed_breakout", "liquidity_exhaustion", "trend_acceptance"]
        },
        "sensors": {
            "absorption_detector": {
                "book_bucket_pct": 0.002,
                "cooldown": 30.0,
                "displacement_z_max": 1.7,
                "level_tolerance_pct": 0.0033,
                "stagnation_floor_pct": 0.0009,
                "volatility_z_max": 2.6,
                "z_score_min": 2.2,
            },
            "failed_breakout": {
                "cooldown": 30.0,
                "divergence_z": 0.8,
                "max_break_age": 150.0,
                "min_break_distance_pct": 0.0022,
            },
            "liquidity_exhaustion": {
                "declining_threshold": 0.5,
                "level_tolerance_pct": 0.0009,
                "min_bounce_pct": 0.0007000000000000001,
                "min_tests": 2,
                "test_memory_seconds": 220.0,
            },
            "trend_acceptance": {
                "cooldown": 240.0,
                "max_pullback_penetration_pct": 0.003,
                "min_candles_outside": 7,
                "pullback_tolerance_pct": 0.0012000000000000001,
            },
        },
        "targets": {
            "failed_breakout": {"sl_pct": 0.020, "tp_pct": 0.070},
            "tactical_absorption": {"sl_pct": 0.020, "tp_pct": 0.070},
            "trend_acceptance": {"sl_pct": 0.010, "tp_pct": 0.070},
            "liquidity_exhaustion": {"sl_pct": 0.020, "tp_pct": 0.070},
        },
    },
    "DOTUSDT": {
        "description": "DOT \u2014 FB+LE+TAV+TA edge confirmed \u2705. LE CVD flip fix, TP1.0/SL2.0.",
        "guardians": {
            "l2_ratio_min": 0.5,
            "l2_ratio_min_trend_acceptance": 1.2000000000000002,
            "l2_ratio_min_trend_down": 2.2,
            "spread_max_ratio": 2.5,
        },
        "optimization_status": {
            "date": "2026-07-17",
            "is_certified": True,
            "method": "optuna",
            "notes": "Par\u00e1metros expl\u00edcitos (overrides) tras refactorizaci\u00f3n.",
        },
        "pressure_thresholds": {"z_block": 2.8},
        "quality_scorer": {
            "grade_thresholds": {"B": 0.4},
            "weights": {"liquidity": 0.1, "regime": 0.3, "spread": 0.05, "structure": 0.15},
        },
        "scenarios": {
            "enabled": ["tactical_absorption", "failed_breakout", "liquidity_exhaustion", "trend_acceptance"]
        },
        "sensors": {
            "absorption_detector": {
                "book_bucket_pct": 0.002,
                "cooldown": 30.0,
                "displacement_z_max": 1.7,
                "level_tolerance_pct": 0.0033,
                "stagnation_floor_pct": 0.0009,
                "volatility_z_max": 2.6,
                "z_score_min": 2.2,
            },
            "failed_breakout": {
                "cooldown": 30.0,
                "divergence_z": 0.8,
                "max_break_age": 150.0,
                "min_break_distance_pct": 0.0022,
            },
            "liquidity_exhaustion": {
                "declining_threshold": 0.5,
                "level_tolerance_pct": 0.0009,
                "min_bounce_pct": 0.0007000000000000001,
                "min_tests": 2,
                "test_memory_seconds": 220.0,
            },
            "trend_acceptance": {
                "cooldown": 240.0,
                "max_pullback_penetration_pct": 0.003,
                "min_candles_outside": 7,
                "pullback_tolerance_pct": 0.0012000000000000001,
            },
        },
        "targets": {
            "failed_breakout": {"sl_pct": 0.008, "tp_pct": 0.005},
            "liquidity_exhaustion": {"sl_pct": 0.003, "tp_pct": 0.012},
            "tactical_absorption": {"sl_pct": 0.003, "tp_pct": 0.012},
            "trend_acceptance": {"sl_pct": 0.009, "tp_pct": 0.009},
        },
    },
}
