"""
Explicit 1:1 Coin Profiles (Overrides Only)
Generated by param_optimizer.py / Refactored
"""

COIN_PROFILES = {
    "AVAXUSDT": {
        "description": "AVAX — all 4 scenarios optimized: tactical "
        "(+0.30→val+0.49) failed_break "
        "(+0.18→val+0.41) liq_exhaust "
        "(-2.94→val+0.29) trend_acc (+0.46)",
        "guardians": {
            "l2_ratio_min": 0.5,
            "l2_ratio_min_failed_breakout": 2.5,
            "l2_ratio_min_liquidity_exhaustion": 1.4,
            "l2_ratio_min_tactical_absorption": 1.2,
            "l2_ratio_min_trend_acceptance": 1.2,
            "l2_ratio_min_trend_down": 2.2,
            "spread_max_ratio": 2.5,
            "spread_max_ratio_failed_breakout": 1.8,
            "spread_max_ratio_liquidity_exhaustion": 1.5,
            "spread_max_ratio_tactical_absorption": 2.4,
            "spread_max_ratio_trend_acceptance": 2.6,
        },
        "optimization_status": {
            "date": "2026-07-17",
            "is_certified": True,
            "method": "optuna",
            "notes": "Parámetros explícitos " "(overrides) tras " "refactorización.",
        },
        "pressure_thresholds": {
            "z_block": 2.8,
            "z_block_failed_breakout": 2.5,
            "z_block_liquidity_exhaustion": 1.6,
            "z_block_tactical_absorption": 1.7,
            "z_block_trend_acceptance": 2.6,
        },
        "quality_scorer": {
            "grade_thresholds": {"B": 0.4},
            "weights": {"liquidity": 0.1, "regime": 0.3, "spread": 0.05, "structure": 0.15},
        },
        "scenarios": {
            "enabled": ["tactical_absorption", "failed_breakout", "liquidity_exhaustion", "trend_acceptance"]
        },
        "sensors": {
            "absorption_detector": {
                "absorption_score_min": 0.275,
                "book_bucket_pct": 0.00075,
                "cooldown": 140.0,
                "displacement_z_max": 3.6,
                "level_tolerance_pct": 0.0039,
                "stagnation_floor_pct": 0.001,
                "volatility_z_max": 2.4,
                "z_score_min": 3.3,
            },
            "failed_breakout": {
                "cooldown": 70.0,
                "divergence_z": 0.6,
                "exhaustion_z": 3.8,
                "max_break_age": 160.0,
                "min_break_distance_pct": 0.001,
            },
            "liquidity_exhaustion": {
                "declining_threshold": 0.98,
                "level_tolerance_pct": 0.0006,
                "min_bounce_pct": 0.0008,
                "min_tests": 2,
                "test_memory_seconds": 170.0,
            },
            "trend_acceptance": {
                "cooldown": 240.0,
                "max_pullback_penetration_pct": 0.003,
                "min_candles_outside": 7,
                "pullback_tolerance_pct": 0.0012,
            },
        },
        "targets": {
            "failed_breakout": {"sl_pct": 0.025, "tp_pct": 0.025},
            "liquidity_exhaustion": {"sl_pct": 0.04, "tp_pct": 0.025},
            "tactical_absorption": {"sl_pct": 0.025, "tp_pct": 0.025},
            "trend_acceptance": {"sl_pct": 0.025, "tp_pct": 0.025},
        },
    },
    "LTCUSDT": {
        "description": "LTC — FB+LE+TAV+TA edge confirmed ✅. LE CVD " "flip fix, TP1.0/SL2.0.",
        "guardians": {
            "l2_ratio_min": 0.5,
            "l2_ratio_min_trend_acceptance": 1.2000000000000002,
            "l2_ratio_min_trend_down": 2.2,
            "spread_max_ratio": 2.5,
        },
        "optimization_status": {
            "date": "2026-07-17",
            "is_certified": True,
            "method": "optuna",
            "notes": "Parámetros explícitos " "(overrides) tras " "refactorización.",
        },
        "pressure_thresholds": {"z_block": 2.8},
        "quality_scorer": {
            "grade_thresholds": {"B": 0.4},
            "weights": {"liquidity": 0.1, "regime": 0.3, "spread": 0.05, "structure": 0.15},
        },
        "scenarios": {
            "enabled": ["tactical_absorption", "failed_breakout", "liquidity_exhaustion", "trend_acceptance"]
        },
        "sensors": {
            "absorption_detector": {
                "book_bucket_pct": 0.002,
                "cooldown": 30.0,
                "displacement_z_max": 1.7,
                "level_tolerance_pct": 0.0033,
                "stagnation_floor_pct": 0.0009,
                "volatility_z_max": 2.6,
                "z_score_min": 2.2,
            },
            "failed_breakout": {
                "cooldown": 30.0,
                "divergence_z": 0.8,
                "max_break_age": 150.0,
                "min_break_distance_pct": 0.0022,
            },
            "liquidity_exhaustion": {
                "declining_threshold": 0.5,
                "level_tolerance_pct": 0.0009,
                "min_bounce_pct": 0.0007000000000000001,
                "min_tests": 2,
                "test_memory_seconds": 220.0,
            },
            "trend_acceptance": {
                "cooldown": 240.0,
                "max_pullback_penetration_pct": 0.003,
                "min_candles_outside": 7,
                "pullback_tolerance_pct": 0.0012000000000000001,
            },
        },
        "targets": {
            "failed_breakout": {"sl_pct": 0.008, "tp_pct": 0.005},
            "liquidity_exhaustion": {"sl_pct": 0.003, "tp_pct": 0.012},
            "tactical_absorption": {"sl_pct": 0.003, "tp_pct": 0.012},
            "trend_acceptance": {"sl_pct": 0.009, "tp_pct": 0.009},
        },
    },
    "SOLUSDT": {
        "description": "SOL — extraído de INERTIAL_TRENDING " "(builder), golden params",
        "optimization_status": {
            "date": "2026-07-17",
            "is_certified": True,
            "method": "optuna",
            "notes": "Parámetros explícitos " "(overrides) tras " "refactorización.",
        },
        "scenarios": {
            "enabled": ["tactical_absorption", "failed_breakout", "liquidity_exhaustion", "trend_acceptance"]
        },
    },
}
