import glob
import json
import os
import subprocess

cluster = "LTC_NOISY_UNCERTAIN_1"
scenarios = ["tactical_absorption", "failed_breakout", "liquidity_exhaustion", "trend_acceptance"]
iterations = 50

optimized_profiles = {}

for scenario in scenarios:
    while True:
        print("\n==============================================")
        print(f"🚀 Running {iterations} iterations for {scenario}...")
        print("==============================================\n")

        result = subprocess.run(
            [
                "python",
                "scripts/cluster_optimizer.py",
                "--cluster",
                cluster,
                "--only",
                scenario,
                "--iterations",
                str(iterations),
            ]
        )

        if result.returncode != 0:
            print(f"❌ Error running optimization for {scenario}. Exiting.")
            exit(1)

        # Find the latest json result to check the score
        list_of_files = glob.glob(f"results/opt_{cluster}_*.json")
        if not list_of_files:
            print("❌ No results found!")
            exit(1)

        latest_file = max(list_of_files, key=os.path.getctime)

        with open(latest_file, "r") as f:
            data = json.load(f)

        best_score = data.get("best_score", -999)
        print(f"\n🎯 Best score for {scenario}: {best_score}")

        opt_file = f"config/coin_profiles_{cluster}_optimized.py"
        if os.path.exists(opt_file):
            optimized_profiles[scenario] = opt_file
            print(f"✅ Saved optimized profile for {scenario}: {opt_file}")

        if best_score > 0:
            print(f"✅ Achieved positive score for {scenario}! Moving to next scenario.")
            break
        else:
            print(
                f"⚠️ Score is still negative ({best_score}). Running another {iterations} iterations for {scenario}..."
            )

print("\n" + "=" * 60)
print("🔧 Merging all optimized scenarios into final profile...")
print("=" * 60)

if len(optimized_profiles) == len(scenarios):
    import copy
    import sys

    sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "config"))
    from coin_profiles import COIN_PROFILES, DEFAULT_PROFILE

    sys.path.pop(0)

    merged = copy.deepcopy(COIN_PROFILES)

    for scenario, opt_file in optimized_profiles.items():
        print(f"\n📋 Merging {scenario} from {opt_file}...")

        opt_module_name = os.path.basename(opt_file).replace(".py", "")
        spec = __import__("importlib.util").util.spec_from_file_location(opt_module_name, opt_file)
        opt_module = __import__("importlib.util").util.module_from_spec(spec)
        spec.loader.exec_module(opt_module)

        opt_profiles = opt_module.COIN_PROFILES

        if cluster in merged and cluster in opt_profiles:
            if "targets" not in merged[cluster]:
                merged[cluster]["targets"] = {}

            if "targets" in opt_profiles[cluster]:
                opt_targets = opt_profiles[cluster]["targets"]
                if scenario in opt_targets:
                    merged[cluster]["targets"][scenario] = opt_targets[scenario]
                    print(
                        f"  ✅ Updated targets for {scenario}: TP={opt_targets[scenario]['tp_pct']:.4f}, SL={opt_targets[scenario]['sl_pct']:.4f}"
                    )

            for key in ["guardians", "pressure_thresholds", "quality_scorer", "sensors"]:
                if key in opt_profiles[cluster]:
                    if key not in merged[cluster]:
                        merged[cluster][key] = {}
                    for subkey, value in opt_profiles[cluster][key].items():
                        merged[cluster][key][subkey] = value

    final_file = f"config/coin_profiles_{cluster}_cascade_merged.py"
    with open(final_file, "w") as f:
        f.write(f'"""\nOptimized for {cluster} via Cascade\nGenerated by cascade.py\n"""\n\n')
        f.write(f"COIN_PROFILES = {json.dumps(merged, indent=4)}\n\n")
        f.write(f'DEFAULT_PROFILE = "{DEFAULT_PROFILE}"\n')

    print(f"\n✅ Merged profile saved to: {final_file}")
    print(f"\n⚠️  REVIEW BEFORE APPLYING:")
    print(f"   1. Check {final_file} for correctness")
    print(f"   2. Manually copy COIN_PROFILES[{cluster}] to config/coin_profiles.py")
    print(f"   3. Or run: cp {final_file} config/coin_profiles.py (if you want to replace ALL profiles)")
else:
    print(f"\n❌ ERROR: Only {len(optimized_profiles)}/{len(scenarios)} scenarios optimized successfully.")
    print("   Optimized:", list(optimized_profiles.keys()))
    print("   Missing:", [s for s in scenarios if s not in optimized_profiles])

print("\n🎉 Cascade optimization complete! All scenarios are positive.")
